apiVersion: v1
kind: ReplicationController
metadata: 
  name: myapp-rc
spec:
  replicas: 3
  selector: 
    app: myapp
    version: 2.5.1

  template:
    metadata:
      labels:
        app: myapp
        version: 2.5.1
    spec:
      containers:
        - name: myapp-container
          image: kr15hna/myjavajenkinsimage07may22:1
          ports: 
            - containerPort: 8080